### ISSUE TITLE
Where do the column numbers start on the sheet?

### ISSUE THREAD

**Issue by domoniquecarter35** [smartsheet-platform/smartsheet-python-sdk#1]
I think the column numbers start after the i on the sheets. Am I right? If that is the case it should be noted somewhere in the documentation. Unless I somehow missed the note.

**Comment by avioing** [comment]
Can you please clarify?
- when you say "on the sheets" are you the user interface or the SDK?
- when you say "documentation" are you referring to the product or SDK
documentation?
Thanks

**Comment by happybob007** [comment]
I'm not certain that I understand the question -- however, the number of columns and rows was a bit of a surprise to me when I was working on the relevant portions of the SDK.

The first column number is 0.
The first row number is 1.

The discrepancy seems to have its origin in rows being "numbered" but columns having an "index".
I just updated the exception that is raised when using row numbers less than 1 -- which might help the library users to make abit more sense of this.

**Comment by domoniquecarter35** [comment]
When I say on the sheets I am talking about the User interface on Smartsheet.
When I say documentation I am talking about the documentation for the SDK. 
I was just a little confused when I tried to get columns and the first column for my particular sheet was priority and not any of the 5 before it. See attached screenshot. 

This isn't a top priority. I just wanted to be sure this was correct. And I feel as if it might be confusing enough to warrant a line in the SDK documentation. Unless it is already there and I missed it. 
![snapshotofssui](https://cloud.githubusercontent.com/assets/6300720/6115516/0aa439f8-b074-11e4-82b3-3441af3ffec4.PNG)

**Comment by avioing** [comment]
Thanks for the suggestion.  You are correct - the only columns API returns
as "columns" are those added / created by users.  There are several row
attributes - like row number, has / has not attachments boolean, has / has
not discussion boolean, has / has not reminders boolean, etc. - that
visually appear as columns in the UI but are not considered data columns.
I will add a note to call this out in our API documentation.

On Mon, Feb 9, 2015 at 12:55 PM, domoniquecarter35 <notifications@github.com
