### ISSUE TITLE
The Discussion object doesn't provide a mechanism to fetch its Attachments or Comments

### ISSUE THREAD

**Issue by happybob007** [smartsheet-platform/smartsheet-python-sdk#10]
The Discussion object is incomplete.
It has no mechanism to fetch any of its Attachments or Comments.
The Discussion objects returned when fetching a Sheet with `discussions=True` is something of scaffold, it doesn't contain any of the Comments.  It also doesn't contain any of the Attachments to the Discussion unless the Sheet was also fetched with `attachments=True`.

There should be a mechanism to fetch the full Discussion object given a partial Discussion object (such as is returned when fetching the Sheet or a a Row).

**Comment by timwellswa** [comment]
I am going to close this...was based upon a v1.1 release.
