### ISSUE TITLE
Add column example/test

### ISSUE THREAD

**Issue by earthmancash2** [smartsheet-platform/smartsheet-python-sdk#101]
I am writing ETL to wipe and rewrite a smartsheet each day based on the content of another smartsheet. As part of that I delete each column with `ss.Sheets.delete_column()`, and then I want to add columns to the sheet and fill out rows.

I found examples of how to write rows in the `test_mock_api_rows.py` file, but I'm having trouble figuring out how to add columns. Here's what I'm trying:

```
test_sheet_id = '1234'
sheet = ss.Sheets.get_sheet(test_sheet_id)

for c in sheet.columns:
    if not c.primary:
        ss.Sheets.delete_column(out_sheet_id, c.id)
    
ss.Sheets.add_columns(out_sheet_id, [
    {'title':'a', 'type': "TEXT_NUMBER", 'index':1}, 
    {'title':'b', 'type': "TEXT_NUMBER", 'index':2}
])
```

This code is able to wipe the columns, but I'm getting this API response when adding the new columns:

```
Response: {
status: 400 Bad Request
content: {
{
    "detail": {
        "columnTitle": null
    },
    "errorCode": 1012,
    "message": "Required object attribute(s) are missing from your request: column.title, column.type, column.index.",
    "refId": "qsuvqbntaixm"
}
}
```

I've tried passing in column jsons using column.title, columnTitle, and title (for each of title, type, index), and nothing has worked. Can you give me a quick example of how I can add columns to a smartsheet?

**Comment by timwellswa** [comment]
```sheet = ss.Sheets.get_sheet(out_sheet_id)
for c in sheet.columns:
    if not c.primary:
        ss.Sheets.delete_column(out_sheet_id, c.id)
ss.Sheets.add_columns(out_sheet_id, [
    smartsheet.models.Column({'title': 'a', 'type': 'TEXT_NUMBER', 'index': 1}),
    smartsheet.models.Column({'title': 'b', 'type': 'TEXT_NUMBER', 'index': 1})
    ])
```
@herronelou had the right answer, use column objects in your array.

BTW, you'll also have to change your example to use the same index. It treats the inserted columns as a group (its and all or nothing request), so basically "add an array of columns at index x". I believe you'll get a message if any one member of the group has a different index. However, it will still insert the columns in the same order as the array (so, in your example, when you get them back, 'a' will be index 1, and 'b' will be index 2).

**Comment by earthmancash2** [comment]
Great, that worked for me! Thank you for the fast response.
