### ISSUE TITLE
Unable to parse request. The following error occurred: Field "createdAt" was of unexpected type.

### ISSUE THREAD

**Issue by sun-pgdx** [smartsheet-platform/smartsheet-python-sdk#106]
Error Message
===========
Error updating rows: {'result': {'errorCode': 1008, 'statusCode': 400, 'code': 1008, 'recommendation': 'Do not retry without fixing the problem. ', 'name': 'ApiError', 'shouldRetry': False, 'refId': 'ldmd8op6jknr', 'message': 'Unable to parse request. The following error occurred: Field "createdAt" was of unexpected type.'}}

Question
=======
Does this suggest that smartsheet-python-sdk 1.3.3 should stop sending the created_at attribute to  Smartsheet API 2.0?

Versions
=======
smartsheet-python-sdk 1.3.3
python 3.5

**Comment by timwellswa** [comment]
The Python SDK is only serializing properties that you set. createdAt is a read-only property and should never be sent in an API request. Can you either provide code around the issue or more logging details on the API request sent?

**Comment by sun-pgdx** [comment]
How do we set the row.created_at = None?
Tried row.created_at(None) and got:
<pre>
TypeError: 'datetime.datetime' object is not callable
</pre>

**Comment by sun-pgdx** [comment]
<pre>
row.created_at = None
</pre>
Seems to have worked.

**Comment by sun-pgdx** [comment]
Now that the **created_at** has been removed, getting the following error:

<pre>
Response: {
  status: 400 Bad Request
  content: {
  {
    "detail": {
        "index": 0,
        "rowId": 3997750849234820
    },
    "errorCode": 1062,
    "message": "Invalid row location: Specify 'above' or 'below' with 'siblingId'. You cannot use other location specifiers in the same request.",
    "refId": "158hr5yhvgil9"
  }
}
</pre>

Unclear how this should be interpreted.
Please advise.

**Comment by timwellswa** [comment]
You must have done a get first? There are potentially several non-settable or undesirable properties of the row returned from a get that shouldn't appear in the update request. I would recommend creating a new row object and only setting or copying the contents that are changing. 

Look here: https://github.com/smartsheet-platform/smartsheet-python-sdk/blob/master/tests/integration/test_rows.py and here: https://github.com/smartsheet-samples/python-read-write-sheet/blob/master/python-read-write-sheet.py for examples

**Comment by sun-pgdx** [comment]
Is this change in expected behavior a known matter?

Is this a change in smartsheet-python-sdk (1.2.0 vs. 1.3.3) or a change in Smartsheet API?

All I did was upgrade smartsheet-python-sdk from 1.2.0 to 1.3.3 - motivated by the Smartsheet TLS 1.1. requirement.

Seems the presence of created_at is new as of 1.3.3.
Seems that setting the value to None causes the update_rows() to not work i.e.: Smartsheet believes it is a new row instead of an existing row.

Am I interpreting this correctly?

**Comment by timwellswa** [comment]
Correct, this is anticipated behavior. This change was made with 1.3.0 in February and is documented in the CHANGELOG.md:

> - In previous releases, property filters were executed prior to create or update operations on many models within the SDK. Unfortunately, those filters were sometimes at odds with the API and occasionally returned unpredictable results. For that reason those filters have been removed. Be aware that any property that is set in a model will be passed through to the API.

To be brutally frank the reason that change was made was to prevent a situation like yours where the user might be relying on potentially incorrect or out-of-date functionality in the SDK. Instead, since the API is by definition always up-to-date, those properties are passed directly through and error checked by the API.

I'm happy to make suggestions if you'd like to paste more details regarding the problematic code.

**Comment by sun-pgdx** [comment]
What do you make of this response error?
<pre>
Response: {
  status: 400 Bad Request
  content: {
  {
    "errorCode": 1008,
    "message": "Unable to parse request. The following error occurred: Field \"createdAt\" was of unexpected type.",
    "refId": "18wsrz13fanz"
  }
}
</pre>

The value is: '2018-05-03 19:21:44+00:00'
The datatype is: <class 'datetime.datetime'>

As per the Smartsheet API documentation the Row object's createdAt attribute has a datatype of timestamp.

Reference: http://smartsheet-platform.github.io/api-docs/?python#row-object

**Comment by timwellswa** [comment]
Let's see what the request looks like that led to that response. 

`logging.basicConfig(level=logging.DEBUG)`
...should dump the request and the request body.

**Comment by sun-pgdx** [comment]
Where is the appropriate place to insert that line of code so that it does not interfere with my current logging scheme?  I seem to get different output behavior when I insert that into my code.

**Comment by timwellswa** [comment]
I have it set at the beginning, but you should be able to put it just previous to the issue in question. The DEBUG log level is pretty verbose, so you should see messages detailing just about all of the components of the request.

**Comment by sun-pgdx** [comment]
Here is the Request payload (I've omitted the cells).
Does the createdAt value look unreasonable?

<pre>
INFO:smartsheet.smartsheet:Request: {
command: PUT https://api.smartsheet.com/2.0/sheets/XXXXXXXXXXXXXXXXX/rows
}
DEBUG:smartsheet.smartsheet:Request Body: {
[
    {
        "cells": [...],
        "createdAt": "2018-05-03T19:21:44+00:00Z",
        "expanded": true,
        "id": XXXXXXXXXXXXXXXX,
        "rowNumber": 2407,
        "siblingId": XXXXXXXXXXXXXXXX
    }
]
}
ERROR:smartsheet.smartsheet:Response: {
  status: 400 Bad Request
  content: {
  {
    "errorCode": 1008,
    "message": "Unable to parse request. The following error occurred: Field \"createdAt\" was of unexpected type.",
    "refId": "qoznjpq949od"
  }
}
</pre>

**Comment by timwellswa** [comment]
Both `createdAt` and `rowNumber` are invalid for PUT(update) operations. Unless you are changing the location of the row, `siblingId` and `expanded` probably don't need to be there either. Note that not all properties of cell are valid during an update either. The API docs contain the valid properties for both cell and row for an update: http://smartsheet-platform.github.io/api-docs/#update-rows. In short, other than the row and column ids, only the properties (and cells) that are changing should be sent in the update request. Your code should look something like:

        # build new cell value
        newCell = smartsheet.models.Cell()
        newCell.column_id = source_column.id
        newCell.value = xyz 

        # build the row to update
        newRow = smartsheet.models.Row()
        newRow.id = source_row.id
        newRow.cells.append(newCell)

        # update
        result = smartsheet.Sheets.update_rows(sheet_id, [newRow])

If you are continuing to have trouble with this, let's please move this issue to support (support@smartsheet.com) where it's easier to have more detailed conversations. You can ask support to loop me (Tim Wells) in.

**Comment by sun-pgdx** [comment]
Thank you.  

We were able to resolve the matter using the approach outlined in your previous post.

Not sure why migration from smartsheet-python-sdk 1.2.0 to smartsheet-python-sdk 1.3.3 required a modification in the implementation of our internal software for using the sdk updates_rows() method- but is what we had to do.
