### ISSUE TITLE
updating row with cellLink()

### ISSUE THREAD

**Issue by anoronh4** [smartsheet-platform/smartsheet-python-sdk#107]
My goal is to populate a second spreadsheet with information from the first sheet using CellLink(). I followed some example code from somewhere, but it doesn't seem to work:

```
def linkcell(client,source_sheetid,source_rowid,source_columnid,dest_columnid):
  cell_link = client.models.CellLink()
  cell_link.sheet_id = source_sheetid
  cell_link.row_id = source_rowid
  cell_link.column_id = source_columnid

  cell = client.models.Cell()
  cell.column_id = dest_columnid
  cell.value=None
  cell.link_in_from_cell = cell_link # cell.value not updated at this step
  return cell

def update_row_wlinks(client,source_rowid,source_sheetid,dest_sheetid):
  get_row(client,source_sheetid,source_rowid)
  new_row = client.models.Row()
  response=client.Sheets.add_rows(dest_sheetid, new_row)
  dest_rowid=response.data[0].to_dict()['id']

  row = client.models.Row()
  row.id = dest_rowid
  for i in id_dict: #id_dict is a dictionary containing mapping of column_ids in sheet A to column_ids in sheet B
    cell=make_link(client,source_sheetid,source_row_id,i,id_dict[i])
    row.cells.append(cell)
  rows = []
  rows.append(row)

  client.Sheets.update_rows(dest_sheetid, rows)

```
at the last line i get the ApiError message: 

> Required object attribute(s) are missing from your request: cell.value.

I've played around with this in a variety of different way and found that cell.value is simply not updated, and I cannot update the row without updating the value. If I do put in a dummy string in cell.value even after linking, it gives me an error.

**Comment by timwellswa** [comment]
Hi, try writing an explicit null to cell.value (None doesn't get serialized, it is ignored, but there is a special object ExplicitNull that will force the serialization of a null in the JSON request):

`cell.value=client.models.ExplicitNull()`

**Comment by timwellswa** [comment]
Here is a full example from the unit tests:
https://github.com/smartsheet-platform/smartsheet-python-sdk/blob/master/tests/integration/test_regression.py

**Comment by timwellswa** [comment]
perfect! I am going to close this issue then.
