### ISSUE TITLE
The Row cache is not refreshed after discard when the Sheet has caching enabled

### ISSUE THREAD

**Issue by happybob007** [smartsheet-platform/smartsheet-python-sdk#11]
Any write operation on a Row invalidates the entire Row cache for the Sheet.

After that, all further Row accesses result in a fetch of the specific Row.

**Comment by happybob007** [comment]
It would be much better if the same subset of Rows (or all of the Rows) were to be fetched and cached after the Row cache is discarded.

Perhaps that behavior (full Row cache reload) should only be done if caching is enabled for the Sheet.

**Comment by timwellswa** [comment]
closing, as this is no longer relevant
