### ISSUE TITLE
SDK doc / code mismatch

### ISSUE THREAD

**Issue by jcwill23** [smartsheet-platform/smartsheet-python-sdk#110]
The Sheet object lists TotalRowCount as an attribute.
In sheet.py, it is total_row_count

Doc lists TotalRowCount in three places.

**Comment by timwellswa** [comment]
Appreciate the issue and you're right, it's not clear in the docs that different conventions were used.

Python convention is to use variables with underscores vs camelCase or mixedCase. However, with the JSON responses, mixedCase is the norm. With the Python SDK, we did our best to stick with Python conventions so there is a camelCase to _underscore translation that occurs on all property names. I have asked for the technical docs to provide some clarification to reflect that language specific conventions are used by the SDKs. 

Per PEP-8 (Python conventions): 
https://www.python.org/dev/peps/pep-0008/#function-and-variable-names

> Function and Variable Names
Function names should be lowercase, with words separated by underscores as necessary to improve readability.

> Variable names follow the same convention as function names.

> mixedCase is allowed only in contexts where that's already the prevailing style (e.g. threading.py), to retain backwards compatibility.

**Comment by jcwill23** [comment]
It isn't about the convention. It is about typing in the example from the help / examples and getting an invalid result and having to open up the associated file directly and read it to figure out the real name (or if there is something wrong with my code)

Craig

**Comment by kfansler** [comment]
As far as I can tell, this is still a conflict between the docs and the actual. The docs always show responses in JSON, where if you’re working solely in the Python SDK, your response values may vary. The SDK’s function is essentially to convert your code to REST + JSON to pass over the wire. REST + JSON comes back from Smartsheet and in varying degrees per SDK is either left as is or converted to values that are readable by the SDK. 

So… yes, this is a documentation convention as far as I can tell. I would need a specific example to fix this exact thing if it is incorrect. That’s not to say that it isn’t confusing. And we are brainstorming ways to make it less confusing. 

The three places in the documentation that show “totalRowCount” are all correct according to the convention we are using. So… can you send me a screenshot of the error you’re seeing? Or give me some other point of data or some additional context? 

We *are* trying to make this easier for you. This feedback is helpful. It’s just a complex problem to solve for multiple languages at once. 

Kevin Fansler | Smartsheet
Senior API Technical Writer
m 2064122671
kevin.fansler@smartsheet.com

**Comment by jcwill23** [comment]
According to the document, this is the attribute

![totalrowcount](https://user-images.githubusercontent.com/25039724/41992999-55ec5636-7a4a-11e8-86d3-96012889cde9.png)

so, I assume that is the name of the attribute.

![errormessage](https://user-images.githubusercontent.com/25039724/41993029-6751d0f4-7a4a-11e8-9fee-80a70ad6e798.png)

but ... it isn't. 
To troubleshoot, I open up the sheet.py and seet what it IS expecting.  
Seems like this is having a recipe that says, '1 tblspoon ApeFeces' and when it is added it tastes, well, like it should, but the chef then says, 'oh that's just a naming convention and everyone knows you should use "Ape_Sugar"
Maybe is is me and my lack of understanding.

Craig

**Comment by kfansler** [comment]
Okay, thanks for the added detail. It helps me see why there’s an issue. I’m going to take this as a “feature request.” We’re exploring a few ideas for fixing it. 


Kevin Fansler | Smartsheet
Senior API Technical Writer
m 2064122671
kevin.fansler@smartsheet.com

**Comment by irwando** [comment]
We are overhauling our docs now.
