### ISSUE TITLE
row.modified_at is always None

### ISSUE THREAD

**Issue by raunakp** [smartsheet-platform/smartsheet-python-sdk#118]
I want to know the modified time for a row. When I read the modified_at property for any row, it is always None.
In order to debug, I get `response.request_response.text`. Here when I parse the JSON, I'm able to read valid modifiedAt property for all rows.
```
response = ss_client.Sheets.get_sheet(
            smSheetInfo['sheetId'],
            include='format,discussions')

 for row in response.rows:
       if row.modified_at:
           print(row.modified_at) # always None, nothing is printed
```

**Comment by timwellswa** [comment]
fixed in my branch. Will merge with next update.
