### ISSUE TITLE
Python 2.7 list_users in users.py error

### ISSUE THREAD

**Issue by AlexandreRenoux** [smartsheet-platform/smartsheet-python-sdk#121]
hi, 

I have un exeption when I call : 
ss_client.Users.list_users(include_all=True) 

error:
line 277, in list_users    response = self._base.request(prepped_request, expected, _op)  File "C:\Python27\lib\site-packages\smartsheet\smartsheet.py", 

I installed all the prerequisites, in python 3.X it works, i try with smarsheet 1.2 and last version..

Thanx for your help

**Comment by timwellswa** [comment]
Can you please post the full error traceback?

**Comment by AlexandreRenoux** [comment]
The error is on azureRM, I think the error is specific to the container system. Using the API via requests it works very well. Thank you for your reply

**Comment by timwellswa** [comment]
Ok, going to close this issue then
