### ISSUE TITLE
Accessing smartsheet data in R

### ISSUE THREAD

**Issue by pranavpandya84** [smartsheet-platform/smartsheet-python-sdk#125]
I am posting this in `python-sdk` since my question may be most relevant here compared to other repos. 

I would like to analyse smartsheet data in **R**. Can someone share some thoughts/ guide me on available options?

**Comment by timwellswa** [comment]
Hi,

I would suggest moving your question over to stackoverflow and tagging it with smartsheet-api. I am not aware of anyone attempting to access Smartsheet using R, but you would be better off asking the question to a broader audience. 

https://stackoverflow.com/questions/ask

**Comment by pranavpandya84** [comment]
Thanks @timwellswa
