### ISSUE TITLE
Support for Python 3.10

### ISSUE THREAD

**Issue by rnag** [smartsheet-platform/smartsheet-python-sdk#173]
I propose that we add support for Python 3.10, if such is feasible enough. As 3.10 has officially been out for a couple of weeks, so I feel it might be worth adding support for 3.10.

One important thing I noticed that seems to break, is that we should use `from collections.abc import ...` instead of `from collections import ...` wherever possible.

I have just tested this with Python 3.10.0 on a Mac OS using the smartsheet-python-sdk latest version (2.105.1) and unable to get it to work. The following is the error I received, in case it's helpful:

```python3
...
    from smartsheet.models import (
venv/lib/python3.10/site-packages/smartsheet/__init__.py:31: in <module>
    from .smartsheet import Smartsheet, fresh_operation, AbstractUserCalcBackoff  # NOQA
venv/lib/python3.10/site-packages/smartsheet/smartsheet.py:34: in <module>
    from .models import Error, ErrorResult
venv/lib/python3.10/site-packages/smartsheet/models/__init__.py:21: in <module>
    from .access_token import AccessToken
venv/lib/python3.10/site-packages/smartsheet/models/access_token.py:20: in <module>
    from ..types import *
venv/lib/python3.10/site-packages/smartsheet/types.py:29: in <module>
    class TypedList(collections.MutableSequence):
E   AttributeError: module 'collections' has no attribute 'MutableSequence'
```

Thanks.

**Comment by tirkarthi** [comment]
PR : https://github.com/smartsheet-platform/smartsheet-python-sdk/pull/174

**Comment by timwellswa** [comment]
pulled
