### ISSUE TITLE
Null date fields

### ISSUE THREAD

**Issue by tberg** [smartsheet-platform/smartsheet-python-sdk#4]
- Adding a new row containing a DATE cell with the value of None results in the following error: APIRequestError status: 400  error_code: 1042  message: u'The value for cell in column 1539813489829764, None, did not conform to the strict requirements for type DATE.'
- Adding a new row containing a DATE cell with the value of "" results in a DATE cell with the value of None.
- An existing row with a DATE cell can have the date value set to None, and when the cell value is fetched it will be None.
- An existing row with a DATE cell can have the date value set to "", and when the cell value is fetched it will be "".

**Comment by tberg** [comment]
Additional testing against the REST api is somewhat at odds with the above.  I've got a script that shows the REST api consuming NULL/None dates without complaints, even in 'strict' mode.  I can send you the script if it would help.

**Comment by happybob007** [comment]
Please send the script.  That's looking like an odd situation.

**Comment by tberg** [comment]
Sorry, didn't see this until just now

On Tue, May 5, 2015 at 2:12 PM, Scott Wimer <notifications@github.com>
wrote:

> Please send the script. That's looking like an odd situation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smartsheet-platform/smartsheet-python-sdk/issues/4#issuecomment-99223085>
> .
>

#!/usr/bin/env python
import requests
import json
import sys

STRICT = True

def short_circuit(r):
  print r
  print r.text
  if r.status_code != 200:
    sys.exit(r.status_code)

def banner(text):
  print
  width = 80
  spare = width - 2 - len(text)
  pad = '#' * (spare / 2)
  txt = '{0} {1} {0}'.format(pad, text)
  print txt

token = "1icmy25o4qyx09rv8rq78svmxe"
headers = {
  'Authorization' : 'Bearer %s' % token,
  'Content-type'  : 'application/json',
}

# create a temp sheet
# needs a date column

sheet_name = 'Date Checker Sheet, Discard'

columns = [
  {'title': 'Primary Key', 'type': 'TEXT_NUMBER', 'primary': True},
  {'title': 'Date', 'type': 'DATE'},
  {'title': 'Value', 'type': 'TEXT_NUMBER'}
]

sheet_conf = {
  'name': sheet_name,
  'columns' : columns,
}

banner("Creating Sheet")
r = requests.post('https://api.smartsheet.com/1.1/sheets', headers=headers, data=json.dumps(sheet_conf))
short_circuit(r)

sheet_info = r.json()
sheet_id = sheet_info['result']['id']
column_ids = {}
for i in sheet_info['result']['columns']:
  id = i['id']
  index = i['index']
  column_ids[index] = id

# add a row with a null date
data = {
  'toBottom': True,
  'rows': [
    {
      'cells': [
        {'columnId': column_ids[0], 'value': None, 'strict': STRICT},
        {'columnId': column_ids[1], 'value': None, 'strict': STRICT},
        {'columnId': column_ids[2], 'value': None, 'strict': STRICT}
      ],
    },      
  ],
}

banner("Adding Null date row")
r = requests.post('https://api.smartsheet.com/1.1/sheet/{0}/rows'.format(sheet_id), headers=headers, data=json.dumps(data))
short_circuit(r)

# add a row with a '' date
data = {
  'toBottom': True,
  'rows': [
    {
      'cells': [
        {'columnId': column_ids[0], 'value': '', 'strict': STRICT},
        {'columnId': column_ids[1], 'value': '', 'strict': STRICT},
        {'columnId': column_ids[2], 'value': '', 'strict': STRICT}
      ],
    },      
  ],
}

banner("Adding empty date row")
r = requests.post('https://api.smartsheet.com/1.1/sheet/{0}/rows'.format(sheet_id), headers=headers, data=json.dumps(data))
short_circuit(r)

# check the value of the date in row 1
banner("Fetching row Null row")
r = requests.get('https://api.smartsheet.com/1.1/sheet/{0}/row/{1}'.format(sheet_id, 1), headers=headers)
short_circuit(r)

# check the value of the date in row 2
banner("Fetching row Empty row")
r = requests.get('https://api.smartsheet.com/1.1/sheet/{0}/row/{1}'.format(sheet_id, 2), headers=headers)
short_circuit(r)

# Delete the sheet
banner("Deleting sheet")
r = requests.delete('https://api.smartsheet.com/1.1/sheet/{0}'.format(sheet_id), headers=headers)
short_circuit(r)

**Comment by timwellswa** [comment]
I am going to close this for now. I can no longer reproduce this issue.
