### ISSUE TITLE
error in Smartsheet.request exception handler

### ISSUE THREAD

**Issue by swtechinsights** [smartsheet-platform/smartsheet-python-sdk#41]
I turned on exceptions with Smartsheet.errors_as_exceptions(True)

I then called Sheet.delete_column() on a column that cannot be deleted.  I got an exception in the error handling code within Smartsheet.request():

Traceback (most recent call last):
[ ... stack trace reduced for clarity ... ]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/smartsheet/sheets.py", line 212, in delete_column
    response = self._base.request(prepped_request, expected, _op)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/smartsheet/smartsheet.py", line 185, in request
    the_ex = native.name
AttributeError: 'Error' object has no attribute 'name'

The code looks like this:
        res = self.request_with_retry(prepped_request, operation)
        native = res.native(expected)

```
    if not self.raise_exceptions:
        return native

    if isinstance(native, self.models.Error):
```

==>     the_ex = native.name
            raise the_ex(native, native.code + ': ' + native.message)
        else:
            return native

The 'native' object has this value:
{"requestResponse": null, "result": {"statusCode": 400, "recommendation": "Do not retry.", "code": 1065, "message": "The column specified cannot be deleted.", "name": "ColumnCannotBeDeletedError", "shouldRetry": false}}

**Comment by timwellswa** [comment]
this has been resolved in pull #56
