### ISSUE TITLE
No way to update selected cells of rows 

### ISSUE THREAD

**Issue by sorensonUber** [smartsheet-platform/smartsheet-python-sdk#42]
[From the API documentation ](https://smartsheet-platform.github.io/api-docs/?shell#update-row%28s%29)it looks like there should be a way to update a subset of cells in a row. However, the [current sdk doesn't seem to support this](https://smartsheet-platform.github.io/api-docs/?python#update-row%28s%29) - update_rows only accepts an list of rows and sheetID. Can this functionality be added?

```
   def update_rows(self, sheet_id, list_of_rows):
        """Update properties of the specified Row.
        Updates cell values in the specified row(s),
        expands/collapses the specified row(s), and/or modifies the
        position of the specified rows (including indenting/outdenting).
        If a row's position is updated, all child rows are moved with the
        row.
        In a parent row, values of the following fields are auto-calculated
        based upon values in the child rows (and therefore cannot be
        updated using the API): Start Date, End Date, Duration, % Complete.
        Args:
            sheet_id (int): Sheet ID
            list_of_rows (list[Row]): Array containing one
                or more Row objects.
        Returns:
            Result
        """
        _op = fresh_operation('update_rows')
        _op['method'] = 'PUT'
        _op['path'] = '/sheets/' + str(sheet_id) + '/rows'
        _op['json'] = list_of_rows
        # filter before we go
        for item in _op['json']:
            item.pre_request_filter = 'update_rows'

        expected = ['Result', 'Row']

        prepped_request = self._base.prepare_request(_op)
        response = self._base.request(prepped_request, expected, _op)

        return response


```

This is an issue because I am unable to update entire rows in my sheet because some cells contain hyperlinks. 

response = smartsheet.Sheets.update_rows(devOnGoingID, [row_2update])

{"requestResponse": null, "result": {"code": 1046, "name": "NotEditableViaApiError", "recommendation": "Do not retry.", "shouldRetry": false, "message": "Cells containing formulas, links to other cells, system values, or Gantt values cannot be inserted or updated through the API, columnId : 6220532535322500", "statusCode": 400}}

(that 'column id' is actually the sheet id.)

**Comment by tblong** [comment]
Just ran into this same issue today.  Formulas were the blocker for me.  I also have the issue of being able to call `update_rows` when the list of rows contains more than one row.  I get the following response error:
```json
{
    "requestResponse": null,
    "result": {
        "code": 1123,
        "name": "MultipleRowLocationSpecificationError",
        "recommendation": "Do not retry without fixing the problem.",
        "shouldRetry": false,
        "message": "Specifying multiple row locations is not yet supported. Each row must use the same row location attribute and value (toBottom, toTop, parentId, siblingId, above)",
        "statusCode": 400
    }
}
```
The workaround for me was just to call `sheets.update_rows(ID, [row])` which defeats the purpose of minimizing calls to the api.

**Comment by tblong** [comment]
@sorensonUber I've found a way to still use the sdk while only updating certain cells in a row where a given row has formulas and things blocking api updates.  

```python
for row in sheet.rows:
    cell = row.get_column(column_id)
    cell.value = 'modified cell value'  # edit the cell locally
    
    # gather more cells and add to list of cells for row...

    # remove all cells in row and just add back the single cell or list of cells
    row.cells = [cell]
    print my_sheets.update_rows(sheet_id, [row])  # update sheet
```

There's still an api call per row for me being able to get things working, but at least there's a way around the issue of only updating certain cells for a given row.

**Comment by sorensonUber** [comment]
Thanks for posting @tblong! annoying that you have to have a call per row, but nice solution.

**Comment by seweil** [comment]
See https://github.com/smartsheet-samples/python-read-write-sheet for an example that updates a single cell in multiple rows. 

It's easier to build your updated cell values (and rows) from scratch, rather than trimming the results of a get.
