### ISSUE TITLE
cannot update rows with indentation

### ISSUE THREAD

**Issue by dchosnek** [smartsheet-platform/smartsheet-python-sdk#44]
When I try to update a row where any one cell is indented, the update call returns the error message `invalidRowLocationError` as show at the bottom of this report. I did a little bit of testing, and it appears that if a group of rows is indented, I can update the **first** one but not the subsequent ones. Because the update_rows method updates the entire row, it really doesn't matter which cell in the row I want to update; I still get the error.

If the following text represents a few rows of a Smartsheet, I've marked which rows I can successfully update and which ones fail.

```
Parent 1      <-- success
Parent 2      <-- success
    Child 1   <-- success
    Child 2   <-- fail
    Child 3   <-- fail
    Child 4   <-- fail
Parent 3      <-- success
```

Here is the error message.

```
{
    "requestResponse": null, 
    "result": {
        "code": 1062, 
        "name": "InvalidRowLocationError", 
        "recommendation": "Do not retry without fixing the problem.", 
        "shouldRetry": false, 
        "message": "Invalid row location.", 
        "statusCode": 400
    }
}
```

**Comment by helver** [comment]
I've just received this error as well.  Any timeline for a fix?

**Comment by timwellswa** [comment]
I believe this will happen if both parent_id and sibling_id are defined. If you copied the existing row, in the case of Child 2 they would both be defined. As a workaround you can set `_sibling_id = None` prior to updating the row.

**Comment by timwellswa** [comment]
This specific issue is closed, but opening a more general issue to evaluate cases where None should be acceptable in property setters.
