### ISSUE TITLE
Workspaces.list_workspaces response includes empty folders, templates, sheets, and reports arrays

### ISSUE THREAD

**Issue by daveskull81** [smartsheet-platform/smartsheet-python-sdk#47]
In the API Documentation for List Workspaces the response for a request via python looks like below:

```
{
    "pageNumber": 1,
    "pageSize": 100,
    "totalPages": 1,
    "totalCount": 2,
    "data": [
        {
            "accessLevel": "OWNER",
            "id": 3457273486960516,
            "name": "workspace 1",
            "permalink": "https://app.smartsheet.com/b/home?lx=JNL0bgXtXc0pzni9tzAc4g"
        },
        {
            "accessLevel": "OWNER",
            "id": 7960873114331012,
            "name": "workspace 2",
            "permalink": "https://app.smartsheet.com/b/home?lx=JLiJbgXtXc0pzni9tzAKiR"
        }
    ]
}
```

The list_workspaces method in the python sdk includes additional arrays for folders, templates, sheets and reports in each workspace object that are always empty regardless of the contents of the workspace:

Request:

```
action = smartsheet.Workspaces.list_workspaces()
workspaces = action.data
print(workspaces[0])
```

Response:

```
{"folders": [], "templates": [], "permalink": "{{PERMALINK}}", "name": "{{WORKSPACE_NAME}}", "sheets": [], "accessLevel": "{{ACCESS_LEVEL}}", "favorite": null, "id": {{WORKSPACE_ID}}, "reports": []}
```

**Comment by timwellswa** [comment]
have noted in the documentation backlog that List Workspaces doc needs to be updated to detail which attributes of the Workspace object are populated during this API call. Marking this as an enhancement as we may be able to do more when working through paging/iterator functionality.
