### ISSUE TITLE
Adding row with numbers results in null values

### ISSUE THREAD

**Issue by daveskull81** [smartsheet-platform/smartsheet-python-sdk#49]
```
import smartsheet
smartsheet = smartsheet.Smartsheet('ACCESS_TOKEN')

row = smartsheet.models.Row()
row.to_top = True
row.cells.append({
    'column_id': COLUMN_ID,
    'value': 1234
})

action = smartsheet.Sheets.add_rows(SHEET_ID, [row])

```

Above code should insert a new row to the top of the sheet with the number 1234 in the cell. Instead no value is entered, a blank row is created, and there is no error reported. Making 1234 a string will allow the value to be inserted, but it comes in as text. There looks to be no way to insert a number using the Python SDK.

**Comment by tblong** [comment]
@daveskull81 Modify the cell's `strict` property to `False` and pass the string version of the number to the api.  I had similar issues of numerics not being updated properly and this worked for me.

```python
import smartsheet
smartsheet = smartsheet.Smartsheet('ACCESS_TOKEN')

row = smartsheet.models.Row()
row.to_top = True
row.cells.append({
    'column_id': COLUMN_ID,
    'value': '1234',
    'strict': False
})

action = smartsheet.Sheets.add_rows(SHEET_ID, [row])
```

**Comment by mriedelumab** [comment]
I'm having a similar issue, but not with new rows. When fetching a cell with an integer value, the 'displayValue' is set, but the 'value' is null:
```
'{
  "columnId": 6787100646369156, 
  "columnType": null,
  "format": null,
  "value": null,
  "hyperlink": null,
  "strict": true,
  "formula": null,
  "linksOutToCells": null,
  "conditionalFormat": null,
  "displayValue": "12345",
  "linkInFromCell": null
}'
```
The API itself is returning appropriate values, however:
```
{
"columnId": 6787100646369156,
"value": 12345,
"displayValue": "12345"
}
```
If I remove the `six` string check from the value setter in `models/cell.py`, it populates the `value` field with a float (so, in the first json snippet, `value` goes from `null` to `12345.0`).
```
    @value.setter
    def value(self, value):
        
        if isinstance(value, six.string_types):
            self._value = value
```
So, if I take out the "if isinstance..." test, the cell loads `12345.0` as the value. If that test is there, the value is `null`. I'm not sure what's causing the `int` to load as a `float`, though.

Any thoughts on this behavior?

**Comment by timwellswa** [comment]
the value setter will now accept type six.string_types, six.integer_types, float and bool. commit #56
