### ISSUE TITLE
multiple include parameters in get_sheet only returns the first listed

### ISSUE THREAD

**Issue by daveskull81** [smartsheet-platform/smartsheet-python-sdk#52]
```
sheet = smartsheet.Sheets.get_sheet(SHEET_ID, include='attachments,discussions,format,ownerInfo')
```

This request will only return the the attachments info and ignore the other items listed in include.

```
sheet = smartsheet.Sheets.get_sheet(SHEET_ID, include='attachments')
```

This request will return the attachments data or other include parameters.

**Comment by Jacko77** [comment]
Hi,

I have created a very rough work around so that multiple include parameters are passed to the url. It is just an extension of get_sheet.

I understand this is in no way elegant, but it does the job for me.

        def get_sheet_with_params(self, sheet_id, include=None, exclude=None, row_ids=None,
                  row_numbers=None, column_ids=None, page_size=100, page=1):
        """Get the specified Sheet.

        Get the specified Sheet. Returns the Sheet, including Rows,
        and optionally populated with Discussion and Attachment
        objects.

        Args:
            sheet_id (int): Sheet ID
            include (list[str]): A comma-separated list of
                optional elements to include in the response. Valid list
                values: attachments, discussions, format, filters,
                ownerInfo, source, rowWriterInfo.
            exclude (str): Response will not include cells
                that have never contained any data.
            row_ids (list[int]): comma-separated list of Row
                IDs on which to filter the rows included in the result.
            row_numbers (list[int]): comma-separated list of
                Row numbers on which to filter the rows included in the
                result. Non-existent row numbers are ignored.
            column_ids (list[int]): comma-separated list of
                Column IDs. The response will contain only the specified
                columns in the 'columns' array, and individual rows' 'cells'
                array will only contain cells in the specified columns.
            page_size (int): The maximum number of items to
                return per page. Defaults to 100.
            page (int): Which page to return. Defaults to 1
                if not specified.

        Returns:
            Sheet
        """
        _op = fresh_operation('get_sheet')
        _op['method'] = 'GET'
        _op['path'] = '/sheets/' + str(sheet_id)
        _op['query_params']['include'] = include
        _op['query_params']['exclude'] = exclude
        _op['query_params']['rowIds'] = row_ids
        _op['query_params']['rowNumbers'] = row_numbers
        _op['query_params']['columnIds'] = column_ids
        _op['query_params']['pageSize'] = page_size
        _op['query_params']['page'] = page



        """Start new code  """
        new_url = str(self._base._api_base) + _op['path'] +  "?"
        if include is not None:
            include_ls = ','.join(map(str, include))
            new_url += "&include=" + include_ls
        if exclude is not None:
            exclude_ls = ','.join(map(str, exclude))
            new_url += "&exclude=" + exclude_ls
        if row_ids is not None:
            rowIds_ls = ','.join(map(str, row_ids))
            new_url += "&rowIds=" + rowIds_ls
        if row_numbers is not None:
            rowNumbers_ls = ','.join(map(str, row_numbers))
            new_url += "&rowNumbers=" + rowNumbers_ls
        if column_ids is not None:
            columnIds_ls = ','.join(map(str, column_ids))
            new_url += "&columnIds" + columnIds_ls
        new_url += "&pageSize" + str(page_size)
        new_url += "&page=" + str(page)

       """End new code"""

        expected = 'Sheet'
        prepped_request = self._base.prepare_request(_op)
        prepped_request.url = new_url  #Replace prepared url with new url
        response = self._base.request(prepped_request, expected, _op)

        return response` 


```

**Comment by timwellswa** [comment]
These are both valid now
```
sheet = smartsheet.Sheets.get_sheet(7947714945148804, include='objectValue,rowWriterInfo,ownerInfo')
sheet = smartsheet.Sheets.get_sheet(6810644029695876, include=['objectValue','rowWriterInfo','ownerInfo'])
```

**Comment by seweil** [comment]
Nice!
