### ISSUE TITLE
`Users.list_users` never returns the lastLogin value

### ISSUE THREAD

**Issue by MrMinos** [smartsheet-platform/smartsheet-python-sdk#62]
In the documentation it states that if you are a system administrator AND if `IndexResult Object` is under 100 `User objects`, you will include the `lastLogin` attribute.

> include (optional): When specified with a value of “lastLogin”, response will include the lastLogin attribute for each user if:
the request is submitted by a system administrator, and
the returned IndexResult object that contains a maximum of 100 User objects.

The python SDK does seem to support `lastLogin` attribute, yet when I try with all sorts of combination the `list_users` function, it always returns `None` for `lastLogin` attribute or does not have the `lastLogin` attribute at all. All the other attributes in the `User object` are returned correctly by the function.

Please point out what I am doing wrong or confirm this issue, I appreciate your help!

**Comment by timwellswa** [comment]
fixed, have PR to pull it into master

**Comment by seweil** [comment]
Fixed in release 1.2.1
