### ISSUE TITLE
Sheet loading defaults do not include attachments, or discussions, (or other stuff)

### ISSUE THREAD

**Issue by happybob007** [smartsheet-platform/smartsheet-python-sdk#9]
The defaults for Sheet load do not fetch the data about attachments, discussions, formats or filters.
This is consistent with the API, but has tripped me and others up on more than one occasion.

It might be less surprising/confusing if the load Sheet methods returned all of the attributes of the Sheet by default (to the extent that they can), but allowed the user to specify that they weren't interested in certain attributes (such as attachments or discussions).

**Comment by timwellswa** [comment]
this was based upon a previous release. Going to close this issue for now, may revisit in the future.
