### ISSUE TITLE
Most of the error messages do not format properly.

### ISSUE THREAD

**Issue by herronelou** [smartsheet-platform/smartsheet-python-sdk#92]
Hi,
Using the SDK in python 2.7, I noticed most of the errors do not actually format properly.
I was wondering why the error messages I was getting were not giving useful information:

> ValueError: `[0]` invalid type for [1] value

Looking at the code, it seems like it's not using the right syntax:
For example, looking at types.py, line 75:
`raise ValueError("Can't convert %s to %s in TypedList", item, self.item_type)`
would need to be:
`raise ValueError("Can't convert %s to %s in TypedList" % (item, self.item_type))`

or line 135:
`raise ValueError("`[0]` invalid type for [1] value".format(value, self.object_type))`
would need to be:
`raise ValueError("`{0}` invalid type for {1} value".format(value, self.object_type))`

**Comment by timwellswa** [comment]
Thanks Erwan. Looks like there might be multiple bad messages in there, likely a result of a poorly done cut and paste. I'll get them addressed in the next update.
